server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka7001.com
  client:
    # 不向注册中心注册自己
    register-with-eureka: true
    # 自己就是注册中心, 不需要检索服务
    fetch-registry: true
    service-url:
      #  查询地址 注册服务 都依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/

